// Types for the build-time module generated by grammarIndex() in vite.config.ts.
declare module "virtual:grammar-index" {
  import type { GrammarLink } from "@/types"
  export const n5: GrammarLink[]
  export const n4: GrammarLink[]
}
